version: "3.4"

services:
  postgres:
    container_name: sampleProject-server
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sampleProject-server
      POSTGRES_PASSWORD: sampleProject-server

volumes:
  postgres_data:
